-- AGRO-MAR CMS + SEO v11

create table if not exists site_settings (
  id bigint primary key default 1,
  company_name text default 'AGRO-MAR Mariusz Bańka Sp. z o.o.',
  hero_title text default 'AGRO-MAR',
  hero_subtitle text default 'Mariusz Bańka Sp. z o.o.',
  hero_lines text default 'Skup owoców|Przetwórstwo|Transport',
  hero_description text default 'Profesjonalny skup owoców, ich przetwórstwo oraz transport krajowy i międzynarodowy.',
  hero_fruit_image text default '/images/owoce-mix.jpg',
  hero_truck_image text default '/images/samochod.jpg',
  phone text default '+48 000 000 000',
  email text default 'kontakt@agro-mar.pl',
  location text default 'Województwo lubelskie, Polska',
  theme text default 'bottle',
  hero_background text default 'bottle',
  seo_title text default 'AGRO-MAR Mariusz Bańka Sp. z o.o. | Skup owoców, przetwórstwo i transport',
  seo_description text default 'AGRO-MAR Mariusz Bańka Sp. z o.o. — skup owoców, przetwórstwo oraz transport ciężki. 10 punktów skupu w województwie lubelskim.',
  updated_at timestamp default now()
);
insert into site_settings (id) values (1) on conflict (id) do nothing;

create table if not exists site_sections (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  menu_label text not null,
  title text not null,
  body text not null,
  sort_order int default 100,
  is_visible boolean default true,
  updated_at timestamp default now()
);

insert into site_sections (slug, menu_label, title, body, sort_order, is_visible) values
('onas','O firmie','Nowoczesna firma z województwa lubelskiego.','AGRO-MAR Mariusz Bańka Sp. z o.o. to prężnie rozwijająca się firma specjalizująca się w skupie i przerobie owoców oraz w transporcie krajowym i międzynarodowym. Posiadamy sieć 10 punktów skupu, nowoczesne zaplecze produkcyjne oraz flotę samochodów ciężarowych.',10,true),
('skup','Skup owoców','Skup owoców','Kupujemy owoce miękkie, pestkowe oraz jabłko przemysłowe. Stawiamy na sprawną obsługę dostaw, przejrzyste warunki współpracy i profesjonalną organizację sezonu.',20,true),
('producent','Dla Producenta Rolnego','Dla Producenta Rolnego','AGRO-MAR Mariusz Bańka Sp. z o.o. od lat współpracuje z producentami rolnymi z województwa lubelskiego oraz całej Polski. Zapewniamy uczciwe warunki współpracy, sprawną organizację skupu, profesjonalną obsługę dostaw, szybki rozładunek oraz stały kontakt z punktami skupu. Zapraszamy do długoterminowej współpracy producentów rolnych oraz grupy producenckie.',25,true),
('transport','Transport','Transport ciężki w Polsce i Europie','Dysponujemy flotą samochodów ciężarowych oraz naczep: firanki standard, chłodnie i cysterny. Realizujemy transport krajowy oraz międzynarodowy.',30,true),
('kontakt','Kontakt','Skontaktuj się z AGRO-MAR','Jeśli jesteś producentem rolnym, kontrahentem lub szukasz transportu, zapraszamy do kontaktu.',40,true)
on conflict (slug) do nothing;

create table if not exists fruits (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text,
  sort_order int default 100,
  is_visible boolean default true
);
insert into fruits (name, image_url, sort_order, is_visible) values
('truskawki','/images/fruit-truskawki.jpg',10,true),
('maliny','/images/fruit-maliny.jpg',20,true),
('porzeczka czarna i czerwona','/images/fruit-porzeczka.jpg',30,true),
('wiśnie','/images/fruit-wisnie.jpg',40,true),
('śliwki','/images/fruit-sliwki.jpg',50,true),
('aronia','/images/fruit-aronia.jpg',60,true),
('jabłko przemysłowe','/images/fruit-jablko-przemyslowe.jpg',70,true),
('jabłko na obierkę','/images/fruit-jablko-obierka.jpg',80,true)
on conflict do nothing;

create table if not exists transport_directions (
  id bigint generated by default as identity primary key,
  name text not null,
  flag text,
  sort_order int default 100,
  is_visible boolean default true
);
insert into transport_directions (name, flag, sort_order, is_visible) values
('Niemcy','🇩🇪',10,true),
('Belgia','🇧🇪',20,true),
('Holandia','🇳🇱',30,true),
('Grecja','🇬🇷',40,true)
on conflict do nothing;

create table if not exists gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text not null,
  sort_order int default 100,
  is_visible boolean default true
);
insert into gallery_items (title, image_url, sort_order, is_visible) values
('Jabłka','/images/jablka.jpg',10,true),
('Owoce','/images/owoce-mix.jpg',20,true),
('Transport','/images/samochod.jpg',30,true)
on conflict do nothing;

alter table site_settings enable row level security;
alter table site_sections enable row level security;
alter table fruits enable row level security;
alter table transport_directions enable row level security;
alter table gallery_items enable row level security;

drop policy if exists "public read settings" on site_settings;
drop policy if exists "public read sections" on site_sections;
drop policy if exists "public read fruits" on fruits;
drop policy if exists "public read directions" on transport_directions;
drop policy if exists "public read gallery" on gallery_items;

create policy "public read settings" on site_settings for select using (true);
create policy "public read sections" on site_sections for select using (true);
create policy "public read fruits" on fruits for select using (true);
create policy "public read directions" on transport_directions for select using (true);
create policy "public read gallery" on gallery_items for select using (true);

drop policy if exists "public write settings" on site_settings;
drop policy if exists "public write sections" on site_sections;
drop policy if exists "public write fruits" on fruits;
drop policy if exists "public write directions" on transport_directions;
drop policy if exists "public write gallery" on gallery_items;

-- Na start proste zapisy z panelu. Docelowo można ograniczyć je do Supabase Auth.
create policy "public write settings" on site_settings for update using (true) with check (true);
create policy "public write sections" on site_sections for all using (true) with check (true);
create policy "public write fruits" on fruits for all using (true) with check (true);
create policy "public write directions" on transport_directions for all using (true) with check (true);
create policy "public write gallery" on gallery_items for all using (true) with check (true);


-- Aktualizacja dla istniejącej bazy po v11
insert into site_sections (slug, menu_label, title, body, sort_order, is_visible)
values ('producent','Dla Producenta Rolnego','Dla Producenta Rolnego','AGRO-MAR Mariusz Bańka Sp. z o.o. od lat współpracuje z producentami rolnymi z województwa lubelskiego oraz całej Polski. Zapewniamy uczciwe warunki współpracy, sprawną organizację skupu, profesjonalną obsługę dostaw, szybki rozładunek oraz stały kontakt z punktami skupu. Zapraszamy do długoterminowej współpracy producentów rolnych oraz grupy producenckie.',25,true)
on conflict (slug) do update set menu_label=excluded.menu_label,title=excluded.title,body=excluded.body,sort_order=excluded.sort_order,is_visible=true;

update fruits set image_url='/images/fruit-truskawki.jpg' where name='truskawki';
update fruits set image_url='/images/fruit-maliny.jpg' where name='maliny';
update fruits set image_url='/images/fruit-porzeczka.jpg' where name='porzeczka czarna i czerwona';
update fruits set image_url='/images/fruit-wisnie.jpg' where name='wiśnie';
update fruits set image_url='/images/fruit-sliwki.jpg' where name='śliwki';
update fruits set image_url='/images/fruit-aronia.jpg' where name='aronia';
update fruits set image_url='/images/fruit-jablko-przemyslowe.jpg' where name='jabłko przemysłowe';
update fruits set image_url='/images/fruit-jablko-obierka.jpg' where name='jabłko na obierkę';


-- Aktualizacja motywów dla istniejącej bazy
alter table site_settings add column if not exists theme text default 'bottle';
update site_settings set theme = coalesce(theme, 'bottle') where id = 1;


-- AGRO-MAR v17: wybór tła bez efektu wyblaknięcia
alter table site_settings add column if not exists hero_background text default 'bottle';
update site_settings set hero_background = coalesce(hero_background, 'bottle') where id = 1;


-- AGRO-MAR v19 — aktualizacja treści transportu i kontaktu
update site_sections
set body = 'AGRO-MAR Mariusz Bańka Sp. z o.o. świadczy usługi transportu krajowego i międzynarodowego.

Transport krajowy realizujemy na terenie Polski.

Transport międzynarodowy realizujemy na terenie Unii Europejskiej, w szczególności na kierunkach: Niemcy, Belgia, Holandia oraz Grecja.

Dysponujemy flotą samochodów ciężarowych oraz naczep: firanki standard, chłodnie i cysterny. Zapewniamy profesjonalną organizację transportu, terminowość dostaw, bezpieczeństwo przewożonych towarów oraz stały kontakt z działem transportu.'
where slug = 'transport';

update site_sections
set
  title = 'Kontakt',
  body = 'Dział zakupu / sprzedaży: 665 423 366

Księgowość / płatności / transport:
724 433 366
695 241 890
669 428 539

E-mail:
admin@agromarbanka.pl
m_banka@op.pl

AGRO-MAR Mariusz Bańka Sp. z o.o.
Kolonia Łaziska 30
24-335 Łaziska
NIP: 7171839598
KRS: 0000984761'
where slug = 'kontakt';
